Repository casangi/astrohack, pull requests merged in 2023-10, with the labels that each got.

#163 Added new algorithm to calculate a suggested number of pixels or cell…
  src/astrohack/_utils/_algorithms.py
  src/astrohack/_utils/_extract_holog.py
  src/astrohack/extract_holog.py
  src/astrohack/mds.py
  tests/unit/test_extract_holog.py
  tests/unit/test_holog.py
  tests/unit/test_panel.py
Labels: Area:SciDev

#166 162 add docstrings to astrohack tests
  src/astrohack/data/_dropbox.py
  tests/unit/test_astrohack_import_template.py
  tests/unit/test_client.py
  tests/unit/test_dio.py
  tests/unit/test_extract_holog.py
  tests/unit/test_extract_locit.py
  tests/unit/test_holog.py
  tests/unit/test_panel.py
Labels: documentation

#167 165 difference method to locit
  docs/cleanup-notebooks.sh
  docs/locit_tutorial.ipynb
  docs/tutorial_vla.ipynb
  docs/visualization_tutorial.ipynb
  etc/casa/post-locit-correct-phases.py
  etc/casa/post-locit-plot-phases.py
  etc/casa/pre-locit-script.py
  src/astrohack/_utils/_locit.py
  src/astrohack/locit.py
  src/astrohack/mds.py
  tests/unit/test_locit.py
Labels: enhancement, Area:SciDev

#170 169 misaligned text in docstrings
  examples/astrohack_ALMA_demo.ipynb
  examples/astrohack_VLA_demo.ipynb
  examples/branch-install-example.ipynb
  examples/example_script.py
  src/astrohack/_utils/_dask_plugins/_astrohack_worker.py
  src/astrohack/_utils/_logger/_astrohack_logger.py
  src/astrohack/_utils/_tools.py
  src/astrohack/client.py
  src/astrohack/combine.py
  src/astrohack/dio.py
  src/astrohack/extract_holog.py
  src/astrohack/extract_pointing.py
  src/astrohack/holog.py
  src/astrohack/locit.py
  src/astrohack/mds.py
  stakeholder_test/alma_stakeholder_test.ipynb
  stakeholder_test/vla_stakeholder_test.ipynb
  tests/stakeholder/reference_test_stakeholder.py
  tests/stakeholder/test_stakeholder_alma.py
  tests/stakeholder/test_stakeholder_vla.py
  tests/unit/test_client.py
  tests/unit/test_locit.py
  tests/unit/test_panel.py
Labels: bug, documentation

#171 161 improve amplitude clipping in panel
  docs/tutorial_vla.ipynb
  docs/visualization_tutorial.ipynb
  src/astrohack/_utils/_panel.py
  src/astrohack/_utils/_panel_classes/antenna_surface.py
  src/astrohack/panel.py
  tests/stakeholder/reference_test_stakeholder.py
  tests/stakeholder/test_stakeholder_alma.py
  tests/stakeholder/test_stakeholder_vla.py
  tests/unit/test_panel.py
Labels: enhancement, Area:SciDev

#175 154 investigate underflow in errors in locit delay fit
  src/astrohack/_utils/_algorithms.py
  src/astrohack/_utils/_locit.py
Labels: bug
