Repository casangi/astrohack, pull requests merged in 2023-05, with the labels that each got.

#69 67 vla otf support
  docs/tutorial_vla.ipynb
  src/astrohack/_utils/_algorithms.py
  src/astrohack/_utils/_extract_holog.py
  src/astrohack/_utils/_holog.py
  src/astrohack/extract_holog.py
  src/astrohack/holog.py
  tests/test_stakeholder.py
Labels: enhancement, Infrastructure

#68 27 to fits
  src/astrohack/_classes/antenna_surface.py
  src/astrohack/_utils/_dask_graph_tools.py
  src/astrohack/_utils/_dio.py
  src/astrohack/_utils/_holog.py
  src/astrohack/_utils/_io.py
  src/astrohack/_utils/_panel.py
  src/astrohack/_utils/_tools.py
  src/astrohack/dio.py
  src/astrohack/holog.py
  src/astrohack/panel.py
Labels: enhancement, Infrastructure

#73 np.matrix deprecation:
  src/astrohack/_utils/_algorithms.py
Labels: bug, Infrastructure

#79 39 resolution element in the aperture plots
  src/astrohack/_classes/antenna_surface.py
  src/astrohack/_utils/_holog.py
  src/astrohack/_utils/_tools.py
  src/astrohack/holog.py
  stakeholder_test/vla_stakeholder_test.ipynb
Labels: Infrastructure, visualization
