Repository casangi/astrohack, pull requests merged in 2023-09, with the labels that each got.

#140 28 locit solver for antenna positions
  docs/api.rst
  docs/locit_tutorial.ipynb
  etc/casa/point-redux.py
  src/astrohack/_utils/_constants.py
  src/astrohack/_utils/_dask_graph_tools.py
  src/astrohack/_utils/_dio.py
  src/astrohack/_utils/_extract_locit.py
  src/astrohack/_utils/_locit.py
  src/astrohack/_utils/_tools.py
  src/astrohack/data/_dropbox.py
  src/astrohack/data/telescopes/aca_7m.zarr/.zattrs
  src/astrohack/data/telescopes/aca_7m.zarr/.zmetadata
  src/astrohack/data/telescopes/alma_da.zarr/.zattrs
  src/astrohack/data/telescopes/alma_da.zarr/.zmetadata
  src/astrohack/data/telescopes/alma_dv.zarr/.zattrs
  src/astrohack/data/telescopes/alma_dv.zarr/.zmetadata
  src/astrohack/data/telescopes/alma_tp.zarr/.zattrs
  src/astrohack/data/telescopes/alma_tp.zarr/.zmetadata
  src/astrohack/data/telescopes/vla.zarr/.zattrs
  src/astrohack/data/telescopes/vla.zarr/.zmetadata
  src/astrohack/data/telescopes/vlba.zarr/.zattrs
  src/astrohack/data/telescopes/vlba.zarr/.zmetadata
  src/astrohack/dio.py
  src/astrohack/locit.py
  src/astrohack/mds.py
Labels: Area:SciDev

#146 141 locit improvements
  src/astrohack/_utils/_constants.py
  src/astrohack/_utils/_extract_locit.py
  src/astrohack/_utils/_locit.py
  src/astrohack/_utils/_tools.py
  src/astrohack/data/telescopes/vla.zarr/.zattrs
  src/astrohack/data/telescopes/vla.zarr/.zmetadata
  src/astrohack/locit.py
  src/astrohack/mds.py
Labels: enhancement, Area:SciDev

#151 142 locit tutorial
  docs/api.rst
  docs/conf.py
  docs/index.rst
  docs/locit_tutorial.ipynb
  src/astrohack/__init__.py
Labels: documentation

#150 148 add usage examples to docstrings of public functions
  docs/api.rst
  docs/locit_tutorial.ipynb
  docs/tutorial_vla.ipynb
  docs/visualization_tutorial.ipynb
  examples/astrohack_ALMA_demo.ipynb
  examples/astrohack_VLA_demo.ipynb
  src/astrohack/__init__.py
  src/astrohack/_utils/_extract_holog.py
  src/astrohack/_utils/_logger/_astrohack_logger.py
  src/astrohack/client.py
  src/astrohack/dio.py
  src/astrohack/extract_holog.py
  src/astrohack/extract_pointing.py
  src/astrohack/holog.py
  src/astrohack/mds.py
  stakeholder_test/alma_stakeholder_test.ipynb
  stakeholder_test/vla_stakeholder_test.ipynb
  tests/stakeholder/reference_test_stakeholder.py
  tests/stakeholder/test_stakeholder_alma.py
  tests/stakeholder/test_stakeholder_vla.py
  tests/unit/test_astrohack_import_template.py
  tests/unit/test_client.py
Labels: documentation

#158 149 write unit tests for astrohackextract locit
  tests/unit/test_extract_locit.py
Labels: Area:Verification

#157 153 add function to plot position corrections on a plot
  docs/locit_tutorial.ipynb
  src/astrohack/_utils/_extract_locit.py
  src/astrohack/_utils/_locit.py
  src/astrohack/_utils/_locit_commons.py
  src/astrohack/mds.py
Labels: visualization, Area:SciDev
