Repository casangi/astrohack, pull requests merged in 2023-12, with the labels that each got.

#191 152 improve documentation of locit and extract locit
  src/astrohack/extract_locit.py
  src/astrohack/locit.py
  src/astrohack/panel.py
Labels: documentation

#192 179 incorporate parameter validation and general logger
  .github/workflows/python-testing-linux.yml
  .github/workflows/python-testing-macos.yml
  .github/workflows/pythonpublish.yml
  docs/locit_tutorial.ipynb
  docs/tutorial_vla.ipynb
  docs/visualization_tutorial.ipynb
  pyproject.toml
  src/astrohack/__init__.py
  src/astrohack/_utils/_algorithms.py
  src/astrohack/_utils/_combine.py
  src/astrohack/_utils/_constants.py
  src/astrohack/_utils/_conversion.py
  src/astrohack/_utils/_dask_graph_tools.py
  src/astrohack/_utils/_dask_plugins/_astrohack_scheduler.py
  src/astrohack/_utils/_dask_plugins/_astrohack_worker.py
  src/astrohack/_utils/_diagnostics.py
  src/astrohack/_utils/_dio.py
  src/astrohack/_utils/_extract_holog.py
  src/astrohack/_utils/_extract_locit.py
  src/astrohack/_utils/_extract_point.py
  src/astrohack/_utils/_holog.py
  src/astrohack/_utils/_imaging.py
  src/astrohack/_utils/_locit.py
  src/astrohack/_utils/_locit_commons.py
  src/astrohack/_utils/_logger/_astrohack_logger.py
  src/astrohack/_utils/_panel.py
  src/astrohack/_utils/_tools.py
  src/astrohack/client.py
  src/astrohack/combine.py
  src/astrohack/config/client.param.json
  src/astrohack/config/combine.param.json
  src/astrohack/config/dask.config.yaml
  src/astrohack/config/extract_holog.param.json
  src/astrohack/config/extract_locit.param.json
  src/astrohack/config/extract_pointing.param.json
  src/astrohack/config/holog.param.json
  src/astrohack/config/locit.param.json
  src/astrohack/config/mds.param.json
  src/astrohack/config/panel.param.json
  src/astrohack/data/_dropbox.py
  src/astrohack/data/_google_drive.py
  src/astrohack/dio.py
  src/astrohack/extract_holog.py
  src/astrohack/extract_locit.py
  src/astrohack/extract_pointing.py
  src/astrohack/holog.py
  src/astrohack/locit.py
  src/astrohack/mds.py
  src/astrohack/panel.py
  stakeholder_test/alma_stakeholder_test.ipynb
  stakeholder_test/vla_stakeholder_test.ipynb
  tests/stakeholder/reference_test_stakeholder.py
  tests/stakeholder/test_stakeholder_alma.py
  tests/stakeholder/test_stakeholder_vla.py
  tests/unit/test_astrohack_import_template.py
  tests/unit/test_client.py
  tests/unit/test_dio.py
  tests/unit/test_extract_locit.py
  tests/unit/test_extract_pointing.py
  tests/unit/test_panel.py
Labels: bug, documentation, Area:Infrastructure

#197 180 memory usage heuristics
  docs/tutorial_vla.ipynb
  examples/branch-install-example.ipynb
  pyproject.toml
  src/astrohack/_utils/_dask_plugins/_astrohack_scheduler.py
  src/astrohack/client.py
  src/astrohack/combine.py
  src/astrohack/data/__init__.py
  src/astrohack/data/datasets.py
  src/astrohack/data/dropbox.py
  src/astrohack/data/google_drive.py
  src/astrohack/dio.py
  src/astrohack/extract_holog.py
  src/astrohack/extract_locit.py
  src/astrohack/extract_pointing.py
  src/astrohack/holog.py
  src/astrohack/locit.py
  src/astrohack/mds.py
  src/astrohack/panel.py
Labels: documentation, enhancement, Area:Infrastructure

#199 196 generalize creation of default file name
  src/astrohack/__init__.py
  src/astrohack/_utils/_dio.py
  src/astrohack/_utils/_tools.py
  src/astrohack/combine.py
  src/astrohack/dio.py
  src/astrohack/extract_holog.py
  src/astrohack/extract_locit.py
  src/astrohack/extract_pointing.py
  src/astrohack/holog.py
  src/astrohack/locit.py
  src/astrohack/mds.py
  src/astrohack/panel.py
  src/astrohack/visualization/viewer.py
  tests/stakeholder/reference_test_stakeholder.py
Labels: Area:Infrastructure

#201 190 port plotting functions to the new parameter checking api
  docs/cleanup-notebooks.sh
  docs/locit_tutorial.ipynb
  docs/tutorial_vla.ipynb
  docs/visualization_tutorial.ipynb
  release_script.py
  src/astrohack/_utils/_combine.py
  src/astrohack/_utils/_constants.py
  src/astrohack/_utils/_dask_graph_tools.py
  src/astrohack/_utils/_dio.py
  src/astrohack/_utils/_extract_holog.py
  src/astrohack/_utils/_extract_locit.py
  src/astrohack/_utils/_holog.py
  src/astrohack/_utils/_locit.py
  src/astrohack/_utils/_panel.py
  src/astrohack/_utils/_param_utils/_check_logger_parms.py
  src/astrohack/_utils/_param_utils/_check_parms.py
  src/astrohack/_utils/_phase_fitting.py
  src/astrohack/_utils/_plot_commons.py
  src/astrohack/_utils/_tools.py
  src/astrohack/combine.py
  src/astrohack/config/create_param_json.py
  src/astrohack/config/mds.param.json
  src/astrohack/extract_holog.py
  src/astrohack/extract_locit.py
  src/astrohack/extract_pointing.py
  src/astrohack/holog.py
  src/astrohack/locit.py
  src/astrohack/mds.py
  src/astrohack/panel.py
Labels: Area:Infrastructure

#202 200 allow panel to select a polarization state
  src/astrohack/_utils/_extract_holog.py
  src/astrohack/_utils/_panel.py
  src/astrohack/_utils/_panel_classes/antenna_surface.py
  src/astrohack/_utils/_panel_classes/base_panel.py
  src/astrohack/_utils/_panel_classes/polygon_panel.py
  src/astrohack/_utils/_panel_classes/telescope.py
  src/astrohack/config/panel.param.json
  src/astrohack/panel.py
  tests/unit/test_class_antenna_surface.py
  tests/unit/test_class_base_panel.py
Labels: enhancement

#209 Fixed astrohack specific worker call in astrohack worker.
  src/astrohack/_utils/_dask_plugins/_astrohack_worker.py
  src/astrohack/_utils/_logger/_astrohack_logger.py
  src/astrohack/_utils/_panel_classes/antenna_surface.py
  src/astrohack/client.py
Labels: bug

#210 Fixed astrohack specific worker call in astrohack worker. This should…
  docs/tutorial_vla.ipynb
  docs/visualization_tutorial.ipynb
  src/astrohack/client.py
Labels: bug
