Repository casangi/astrohack, pull requests merged in 2023-07, with the labels that each got.

#115 109 fix heuristic that calculates grid parameters for vla otf mosaics
  src/astrohack/_utils/_algorithms.py
Labels: bug, Area:Infrastructure

#112 Fix the problem of overwrite and reuse_pointing having an 'undesireab…
  src/astrohack/_utils/_extract_holog.py
  src/astrohack/extract_holog.py
Labels: bug, Area:Infrastructure

#116 104 define the ci pipeline for pushes to branches
  .github/workflows/python-testing-linux.yml
  pyproject.toml
  tests/unit/test_astrohack_import_template.py
Labels: Area:Verification

#121 113 separation of extract holog and extract pointing
  docs/tutorial_vla.ipynb
  docs/visualization_tutorial.ipynb
  src/astrohack/__init__.py
  src/astrohack/_utils/_algorithms.py
  src/astrohack/_utils/_dio.py
  src/astrohack/_utils/_extract_holog.py
  src/astrohack/_utils/_extract_point.py
  src/astrohack/_utils/_holog.py
  src/astrohack/_utils/_logger/_astrohack_logger.py
  src/astrohack/_utils/_param_utils/__init__.py
  src/astrohack/_utils/_param_utils/_check_logger_parms.py
  src/astrohack/_utils/_param_utils/_check_parms.py
  src/astrohack/_utils/_tools.py
  src/astrohack/astrohack_client.py
  src/astrohack/combine.py
  src/astrohack/extract_holog.py
  src/astrohack/extract_pointing.py
  src/astrohack/gdown_utils.py
  src/astrohack/holog.py
  src/astrohack/mds.py
  src/astrohack/panel.py
  stakeholder_test/alma_stakeholder_test.ipynb
  stakeholder_test/vla_stakeholder_test.ipynb
  tests/stakeholder/reference_test_stakeholder.py
  tests/stakeholder/test_stakeholder_alma.py
  tests/stakeholder/test_stakeholder_vla.py
Labels: enhancement, Area:Infrastructure
