Repository casangi/astrohack, pull requests merged in 2023-06, with the labels that each got.

#82 72 refactoring of functions and classes in io and dio
  docs/tutorial_vla.ipynb
  src/astrohack/__init__.py
  src/astrohack/_classes/antenna_surface.py
  src/astrohack/_classes/base_panel.py
  src/astrohack/_utils/__init__.py
  src/astrohack/_utils/_combine.py
  src/astrohack/_utils/_constants.py
  src/astrohack/_utils/_dask_graph_tools.py
  src/astrohack/_utils/_diagnostics.py
  src/astrohack/_utils/_dio.py
  src/astrohack/_utils/_extract_holog.py
  src/astrohack/_utils/_extract_point.py
  src/astrohack/_utils/_holog.py
  src/astrohack/_utils/_imaging.py
  src/astrohack/_utils/_io.py
  src/astrohack/_utils/_mds.py
  src/astrohack/_utils/_panel.py
  src/astrohack/_utils/_parm_utils/_check_logger_parms.py
  src/astrohack/_utils/_parm_utils/_check_parms.py
  src/astrohack/_utils/_phase_fitting.py
  src/astrohack/_utils/_tools.py
  src/astrohack/combine.py
  src/astrohack/diagnostics.py
  src/astrohack/dio.py
  src/astrohack/extract_holog.py
  src/astrohack/holog.py
  src/astrohack/panel.py
  stakeholder_test/vla_stakeholder_test.ipynb
  tests/test_class_antenna_surface.py
  tests/test_stakeholder.py
Labels: Infrastructure

#86 71 visualization tutorial
  docs/index.rst
  docs/tutorial_vla.ipynb
  docs/visualization_tutorial.ipynb
  src/astrohack/_classes/antenna_surface.py
  src/astrohack/_utils/_constants.py
  src/astrohack/_utils/_dask_graph_tools.py
  src/astrohack/_utils/_holog.py
  src/astrohack/_utils/_mds.py
  src/astrohack/_utils/_panel.py
Labels: documentation, enhancement, Infrastructure

#98 94 move panel related classes to utils folder
  docs/conf.py
  docs/visualization_tutorial.ipynb
  src/astrohack/_utils/_holog.py
  src/astrohack/_utils/_mds.py
  src/astrohack/_utils/_panel.py
  src/astrohack/_utils/_panel_classes/antenna_surface.py
  src/astrohack/_utils/_panel_classes/base_panel.py
  src/astrohack/_utils/_panel_classes/polygon_panel.py
  src/astrohack/_utils/_panel_classes/ring_panel.py
  src/astrohack/_utils/_panel_classes/telescope.py
  src/astrohack/panel.py
  tests/test_class_antenna_surface.py
  tests/test_class_base_panel.py
  tests/test_class_ring_panel.py
  tests/test_class_telescope.py
Labels: Area:Infrastructure

#107 benchmarking test framework
  asv.conf.json
  benchmarks/__init__.py
  benchmarks/benchmarks.py
Labels: Area:Infrastructure

#111 105 test template file
  tests/stakeholder/test_stakeholder.py
  tests/unit/test_astrohack_import_template.py
  tests/unit/test_class_antenna_surface.py
  tests/unit/test_class_base_panel.py
  tests/unit/test_class_ring_panel.py
  tests/unit/test_class_telescope.py
Labels: Area:Verification

#110 106 add test holog image panel files to google download function
  src/astrohack/combine.py
  src/astrohack/gdown_utils.py
  tests/stakeholder/test_stakeholder.py
Labels: enhancement, Area:Infrastructure, Area:Verification
