Repository casangi/astrohack, pull requests merged in 2024-09, with the labels that each got.

#266 261 implement aips flexible method for panel fitting
  src/astrohack/antenna/antenna_surface.py
  src/astrohack/antenna/base_panel.py
  src/astrohack/antenna/panel_fitting.py
  src/astrohack/antenna/polygon_panel.py
  src/astrohack/antenna/ring_panel.py
  src/astrohack/panel.py
  src/astrohack/utils/validation.py
  tests/unit/test_class_antenna_surface.py
  tests/unit/test_class_base_panel.py
  tests/unit/test_class_ring_panel.py
Labels: enhancement, Area:SciDev

#269 268 replace graphviper dependency
  benchmarks/benchmarks.py
  docs/locit_tutorial.ipynb
  docs/tutorial_vla.ipynb
  docs/visualization_tutorial.ipynb
  etc/alma-nf-filler/readme.org
  examples/astrohack_ALMA_demo.ipynb
  examples/astrohack_VLA_demo.ipynb
  examples/branch-install-example.ipynb
  examples/example_script.py
  pyproject.toml
  src/astrohack/__init__.py
  src/astrohack/antenna/antenna_surface.py
  src/astrohack/antenna/base_panel.py
  src/astrohack/antenna/panel_fitting.py
  src/astrohack/antenna/telescope.py
  src/astrohack/combine.py
  src/astrohack/core/combine.py
  src/astrohack/core/extract_holog.py
  src/astrohack/core/extract_locit.py
  src/astrohack/core/extract_pointing.py
  src/astrohack/core/holog.py
  src/astrohack/core/locit.py
  src/astrohack/core/panel.py
  src/astrohack/dio.py
  src/astrohack/extract_holog.py
  src/astrohack/extract_locit.py
  src/astrohack/extract_pointing.py
  src/astrohack/holog.py
  src/astrohack/locit.py
  src/astrohack/mds.py
  src/astrohack/panel.py
  src/astrohack/utils/algorithms.py
  src/astrohack/utils/conversion.py
  src/astrohack/utils/data.py
  src/astrohack/utils/file.py
  src/astrohack/utils/fits.py
  src/astrohack/utils/graph.py
  src/astrohack/utils/gridding.py
  src/astrohack/utils/imaging.py
  src/astrohack/utils/phase_fitting.py
  src/astrohack/utils/text.py
  src/astrohack/utils/tools.py
  src/astrohack/utils/veritas.py
  src/astrohack/visualization/diagnostics.py
  src/astrohack/visualization/fits.py
  src/astrohack/visualization/textual_data.py
  stakeholder_test/alma_stakeholder_test.ipynb
  stakeholder_test/vla_stakeholder_test.ipynb
  tests/stakeholder/_test_stakeholder_alma.py
  tests/stakeholder/reference_test_stakeholder.py
  tests/stakeholder/test_stakeholder_vla.py
  tests/unit/test_class_antenna_surface.py
  tests/unit/test_combine.py
  tests/unit/test_dio.py
  tests/unit/test_extract_holog.py
  tests/unit/test_extract_locit.py
  tests/unit/test_extract_pointing.py
  tests/unit/test_holog.py
  tests/unit/test_locit.py
  tests/unit/test_panel.py
Labels: enhancement, Area:Infrastructure

#275 Added RMS value beofre and after adjustments to gain tables exported …
  docs/visualization_tutorial.ipynb
  src/astrohack/antenna/antenna_surface.py
  src/astrohack/antenna/panel_fitting.py
  src/astrohack/config/mds.param.json
  src/astrohack/mds.py
  src/astrohack/visualization/textual_data.py
Labels: enhancement, visualization
