Repository casangi/astrohack, pull requests merged in 2024-01, with the labels that each got.

#216 214 fits images
  src/astrohack/_utils/_dio.py
  src/astrohack/_utils/_holog.py
  src/astrohack/_utils/_panel_classes/antenna_surface.py
  src/astrohack/_utils/_tools.py
Labels: bug

#217 211 test protoype logger
  examples/branch-install-example.ipynb
  src/astrohack/__init__.py
  src/astrohack/_utils/_algorithms.py
  src/astrohack/_utils/_combine.py
  src/astrohack/_utils/_conversion.py
  src/astrohack/_utils/_dask_graph_tools.py
  src/astrohack/_utils/_dask_plugins/__init__.py
  src/astrohack/_utils/_dio.py
  src/astrohack/_utils/_extract_holog.py
  src/astrohack/_utils/_extract_locit.py
  src/astrohack/_utils/_extract_point.py
  src/astrohack/_utils/_holog.py
  src/astrohack/_utils/_imaging.py
  src/astrohack/_utils/_locit.py
  src/astrohack/_utils/_locit_commons.py
  src/astrohack/_utils/_panel.py
  src/astrohack/_utils/_tools.py
  src/astrohack/_utils/plugins/__init__.py
  src/astrohack/_utils/plugins/scheduler.py
  src/astrohack/_utils/plugins/worker.py
  src/astrohack/client.py
  src/astrohack/combine.py
  src/astrohack/data/datasets.py
  src/astrohack/data/dropbox.py
  src/astrohack/dio.py
  src/astrohack/extract_holog.py
  src/astrohack/extract_locit.py
  src/astrohack/extract_pointing.py
  src/astrohack/holog.py
  src/astrohack/locit.py
  src/astrohack/mds.py
  src/astrohack/panel.py
Labels: enhancement, Area:Infrastructure

#229 226 dropped antenna may mess antenna ordering in extract pointing
  src/astrohack/_utils/_extract_point.py
Labels: bug

#227 218 uvhol holog mds filler
  src/astrohack/_utils/_extract_holog.py
  src/astrohack/config/mds.param.json
  src/astrohack/mds.py
Labels: enhancement, Area:SciDev

#228 223 filter out scans with the system configuration subintent in extract pointing and extract holog
  src/astrohack/_utils/_extract_point.py
  src/astrohack/_utils/_tools.py
  src/astrohack/extract_holog.py
Labels: enhancement, Area:SciDev

#230 Changed how the input parameters, grid_size and cell_size, are handle…
  src/astrohack/config/holog.param.json
  src/astrohack/extract_holog.py
  src/astrohack/holog.py
Labels: bug, Area:Infrastructure
